[package]
name = "insult_generator"
version = "0.1.0"
authors = ["Kevin MacPherson <kevin.macpherson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"